<h1>Output</h1>

In [2]:
print("Hello World")

Hello World


<h1>Data Structures</h1>

In [25]:
# Array
array = ['Hi', 103]
print('This is an array: ',array)

This is an array:  ['Hi', 103]


In [21]:
#List
list = ['Hi',103,]
print('This is a list: ',list)

This is a list:  ['Hi', 103]


In [19]:
#tuples
tuple = ('Hi',103)
print('This is a tuple: ',tuple)

This is a tuple:  (1, 2, 'Hi')


In [17]:
#set
set = {'Hi',103}
print('This is a set: ',set)

This is a set:  {'Hi', 103}


In [27]:
#dictionary
dictionary = {'Name':'Umair Abid',
              'Gender':'Male',
              'Age':25
             }
print(dictionary)
              

{'Name': 'Umair Abid', 'Gender': 'Male', 'Age': 25}


In [29]:
#input from user
name = input("Enter your name.")
print("Good Morning,",name)

Enter your name. Umair


Good Morning, Umair


In [33]:
#xor operator
print(2^2)  # it convert both into binary and then comapare both or same or not

0


In [35]:
print(2^3)

1


In [39]:
#memborship operator
print('P' in 'Pakistan')

True


In [47]:
# challenge 1
string = input("Enter the string: ")
print("You have entered: ",string)

reversed_string = ""

for index in range(len(string)-1,-1,-1):
    
    reversed_string+=string[index]
    
print(reversed_string)

Enter the string:  Hi, there this is pyhton


You have entered:  Hi, there this is pyhton
nothyp si siht ereht ,iH


In [85]:
# challenge 2 Check Palindrome
def is_palindrome(string):
    # remove spaces and  convert into lower case
    lower = string.replace(" ","").lower()

    reversed_string = ""
    
    # reverse the string
    for index in range(len(lower)-1,-1,-1):
        #print every iteration
        print(f"{index},    {reversed_string} = {reversed_string} + {lower[index]}")
        reversed_string+=lower[index]
    return lower == reversed_string  #(reversed_string) and returns True if they match, otherwise False.

# taking a string input from user
input_string = input("Enter the string: ")
if is_palindrome(input_string):
    print(f"This string '{input_string}' is  palindrome")
else:
    print(f"This string '{input_string}' isn't palindrome")

Enter the string:  Pakistan


7,     =  + n
6,    n = n + a
5,    na = na + t
4,    nat = nat + s
3,    nats = nats + i
2,    natsi = natsi + k
1,    natsik = natsik + a
0,    natsika = natsika + p
This string 'Pakistan' isn't palindrome


In [83]:
#factorial

def factorial(number):
    if number<0:
        print("Factorial is not defined for negative numbers.")
    result = 1
    for index in range(1,number+1):
        print(f"{index},    {result}= {result}*{index}")
        result = result*index
        
    return result

number = int(input("Enter a Number: "))
print(f"The factorial of {number} is {factorial(number)}.")

Enter a Number:  5


1,    1= 1*1
2,    1= 1*2
3,    2= 2*3
4,    6= 6*4
5,    24= 24*5
The factorial of 5 is 120.


In [95]:
number = int(input("Enter the number of Month: "))

if number == 1:
    print("January")
elif number == 2:
    print("February")
elif number == 3:
    print("March")
elif number == 4:
    print("April")
elif number == 5:
    print("May")
elif number == 6: 
    print("June")
elif number == 7:
    print("July")
elif number == 8:
    print("August")
elif number == 9:
    print("September")
elif number == 10:
    print("October")
elif number == 11:
    print("November")
elif number == 12:
    print("December")
else:
    print("invalid number")
    

Enter the number of Month:  7


July


In [103]:
def table(num):

    for index in range(1,11):
        print(f"{num} * {index} = {num*index}")

num = int(input("Enter a number."))
table(num)

Enter a number. 2


2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20


In [105]:
import numpy as np

In [107]:
arr = np.array([1,2,3,4,5])

In [109]:
arr

array([1, 2, 3, 4, 5])

In [111]:
type(arr)

numpy.ndarray

In [113]:
arr.shape

(5,)

In [119]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [121]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [123]:
arr.shape

(3, 5)

In [141]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [153]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [155]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [181]:
arr = np.array([[1,2,3,4,5]])

print(f"1. Array = {arr}")
print(f"2. Dimensions = {arr.ndim}")
print(f"3. Size = {arr.size}")
print(f"4. Shape = {arr.shape}")
print(f"5. Item Size = {arr.itemsize}")
print(f"6. Data Type = {arr.dtype}")

1. Array = [[1 2 3 4 5]]
2. Dimensions = 2
3. Size = 5
4. Shape = (1, 5)
5. Item Size = 8
6. Data Type = int64


In [187]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

addition = arr+arr2

In [189]:
print(addition)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]
